### ISSUE TITLE
BlurMaskFilter for progress arc is too performance heavy

### ISSUE THREAD

**Issue by Ornolfr** [AppSci/SleepTimePicker#2]
The more expanded the progress arc is, the more time it takes to draw the blur effect. You can see the performance hit here:
[Video](https://streamable.com/nh7r1)

Here's the problematic code that I measured:
```
    private fun drawProgress(canvas: Canvas) {
        val startAngle = -sleepAngle.toFloat()
        val sweep = Utils.to_0_360(sleepAngle - wakeAngle).toFloat()
        val time = measureTimeMillis {
            progressBottomBlurPaint?.let {
                canvas.drawArc(circleBounds, startAngle, sweep, false, it)
            }
            progressTopBlurPaint?.let {
                canvas.drawArc(circleBounds, startAngle, sweep, false, it)
            }
        }
        Log.e("TAG", "Time = $time")
        
        canvas.drawArc(circleBounds, startAngle, sweep, false, progressPaint)
    }
```
Execution time differs wildly depending on how big of an interval is chosen. On my device, it grew from 2ms to 100ms. On Pixel, it goes from 1ms to 25-30ms. Basically, the weaker the device the bigger FPS drop it would get. 

Commenting out these lines fixed the problem for me:
`progressTopBlurPaint!!.maskFilter = BlurMaskFilter(topBlurRadius, BlurMaskFilter.Blur.NORMAL)`
`progressBottomBlurPaint!!.maskFilter = BlurMaskFilter(bottomBlurRadius, BlurMaskFilter.Blur.NORMAL)`

**Comment by dima-ostapovets** [comment]
Thank you. 
To improve performance you can remove -shadow- attributes from layout xml. 
Probably glow will be removed in next version.

**Comment by dmytro-ostapovets** [comment]
Feel free to open new issue or make PR if you still have this problem.
